name: PowerTower
version: ${project.version}
description: ${plugin-description}
api-version: ${spigot-api-version}
authors: [DPOH-VAR, MYXOMOPX]
database: false
main: ru.flinbein.powertower.PowerTowerPlugin

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlin-std-lib-version}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlin-std-lib-version}
depend:
  - PowerNBT
  - FurnitureLib
  - Vault

commands:
  powertower:
    description: some settings?
    aliases: ['twr']
    usage: /powertower
    permission: powertower.command